#!/bin/bash
#
# iptables example configuration script

# IPv4 general configuration settings
# ===================================
# Drop ICMP echo-request messages sent to broadcast or multicast addresses
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
# Drop source routed packets
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route
# Enable TCP SYN cookie protection from SYN floods
echo 1 > /proc/sys/net/ipv4/tcp_syncookies
# Don't accept ICMP redirect messages
echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects
# Don't send ICMP redirect messages
echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects
# Enable source address spoofing protection
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
# Log packets with impossible source addresses
echo 1 > /proc/sys/net/ipv4/conf/all/log_martians

# IPv6 general configuration settings
# Unfortunately, /proc/sys/net/ipv6 has slightly different
# directory structure
# ===================================
# Drop ICMP echo-request messages sent to broadcast or multicast addresses
echo 1 > /proc/sys/net/ipv6/icmp/echo_ignore_multicast
echo 1 > /proc/sys/net/ipv6/icmp/echo_ignore_anycast
# Drop source routed packets
echo 0 > /proc/sys/net/ipv6/conf/all/accept_source_route
# Enable TCP SYN cookie protection from SYN floods
#echo 1 > /proc/sys/net/ipv6/tcp_syncookies
# Don't accept ICMP redirect messages
echo 0 > /proc/sys/net/ipv6/conf/all/accept_redirects
# Don't send ICMP redirect messages
#echo 0 > /proc/sys/net/ipv6/conf/all/send_redirects
# Enable source address spoofing protection
#echo 1 > /proc/sys/net/ipv6/conf/all/rp_filter
# Log packets with impossible source addresses
#echo 1 > /proc/sys/net/ipv6/conf/all/log_martians

# Firewall rules 
# ==============
# Use same rules for both IPv4 and IPv6
for ip_version in 4 6; do
    case ${ip_version} in
        6)  cmd="/sbin/ip6tables"
            icmp="icmpv6"
            ;;
        *)  cmd="/sbin/iptables"
            icmp="icmp"
            ;;
    esac
        
    # Flush all chains
    ${cmd} --flush
 
    # Allow unlimited traffic on the loopback interface
    ${cmd} -A INPUT -i lo -j ACCEPT
    ${cmd} -A OUTPUT -o lo -j ACCEPT
 
    # Set default policies
    ${cmd} --policy INPUT DROP
    ${cmd} --policy OUTPUT DROP
    ${cmd} --policy FORWARD DROP
 
    # Allow unlimited outbound traffic
    ${cmd} -A OUTPUT -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
    
    # Previously initiated and accepted exchanges bypass rule checking
    ${cmd} -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
 
    # Rate-limit SSH for attack protection
    ${cmd} -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 4 -j DROP
    ${cmd} -A INPUT -p tcp --dport 22 -m state --state NEW -m recent --set
    ${cmd} -A INPUT -p tcp --dport 22 -m state --state NEW -j ACCEPT
 
    # Allow certain ports to be accessible from the outside
    # ${cmd} -A INPUT -p tcp --dport 80 -m state --state NEW -j ACCEPT    # http
    # ${cmd} -A INPUT -p tcp --dport 443 -m state --state NEW -j ACCEPT   # https
    # ${cmd} -A INPUT -p udp --dport 5021 -m state --state NEW -j ACCEPT

    # Allow pinging
    ${cmd} -A INPUT -p ${icmp} --${icmp}-type echo-request -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
  
    # Drop all other traffic
    ${cmd} -A INPUT -j DROP

    # Display the rules
    echo "*** Rules for IPv${ip_version} ***"
    ${cmd} -nvL
    echo

# End of firewall rules
done
