#!/bin/bash
#
# Disable all firewall rules

# Set both IPv4 and IPv4 firewalls to same states
for ip_version in 4 6; do
    case ${ip_version} in
        6)  cmd="/sbin/ip6tables" ;;
        *)  cmd="/sbin/iptables" ;;
    esac
    ${cmd} -F
    ${cmd} -X
    ${cmd} -t nat -F
    ${cmd} -t nat -X
    ${cmd} -t mangle -F
    ${cmd} -t mangle -X
    ${cmd} -P INPUT ACCEPT
    ${cmd} -P FORWARD ACCEPT
    ${cmd} -P OUTPUT ACCEPT
    echo "*** Firewall rules for IPv${ip_version} ***"
    ${cmd} -nvL
    echo
done
