#!/bin/bash
iptables=$(which iptables)

${iptables} -F
${iptables} -X
${iptables} -t nat -F
${iptables} -t nat -X
${iptables} -t mangle -F
${iptables} -t mangle -X

# the rules allow us to reconnect by opening up all traffic.
${iptables} -P INPUT ACCEPT
${iptables} -P FORWARD ACCEPT
${iptables} -P OUTPUT ACCEPT

# print out all rules to the console after running this file.
${iptables} -nL
